# ExternalServiceInit 配置文件
# 外部服务管理器专用配置

# 核心LLM配置
LLM_model:
  name: llama3.2 # ollama运行的模型名称(必须在ollama中支持并且可以运行的)

# 外部服务配置
external_services:
  # 要启动的基础外部服务
  base_services:
  
    - Consul:
        script: "consul"
        service_name: "Consul"
        conda_env: "/home/yomu/data/anaconda3/envs"
        # args: ["agent", "-server", "-bind=127.0.0.1", "-client=127.0.0.1",
        # "-bootstrap-expect=3" ,"-node=consul-server-01" ,
        # "-data-dir=/home/yomu/data/consul_data/server01",
        # "-join=127.0.0.1:8300" ,"-http-port=8500" ,"-rpc-port=8300" ,"-server-port=8300"]
        args: ["agent", "-dev", "-client", '{{ GetPrivateInterfaces | exclude "type" "ipv6" | join "address" " " }} {{ GetAllInterfaces | include "flags" "loopback" | join "address" " " }}']
        use_python: false
        run_in_background: true
        is_base: true
        log_file: "Consul.log"
        startup_timeout: 30
        health_check_url: "http://127.0.0.1:8500/v1/status/leader"

    - ollama_server:
        script: "ollama"
        service_name: "ollama_server"
        conda_env: "/home/yomu/data/anaconda3/envs"
        args: ["serve"]
        use_python: false
        run_in_background: true
        is_base: true
        log_file: "ollama_server.log"
        startup_timeout: 60
        health_check_url: "http://127.0.0.1:11434/api/tags"

    - GPTSoVits_server:
        script: "/home/yomu/GPTSoVits/GPTSoVits_api.py"
        service_name: "GPTSoVits_server"
        conda_env: "/home/yomu/data/anaconda3/envs/GPTSoVits"
        args: ["-a", "0.0.0.0","-p","9880"]
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "GPTSoVits_server.log"
        startup_timeout: 90
        health_check_url: "http://127.0.0.1:9880/health"

    - SenseVoice_server:
        script: "/home/yomu/SenseVoice/SenseVoice_server.py"
        service_name: "SenseVoice_server"
        conda_env: "/home/yomu/data/anaconda3/envs/SenseVoice"
        args: []
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "SenseVoice_server.log"
        startup_timeout: 60
        health_check_url: "http://127.0.0.1:20042/health"

    - MicroServiceGateway:
        script: "/home/yomu/agent/Service/Gateway/MicroServiceGateway.py"
        service_name: "MicroServiceGateway"
        conda_env: "/home/yomu/data/anaconda3/envs/agent"
        args: []
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "MicroServiceGateway.log"
        startup_timeout: 30
        health_check_url: "http://127.0.0.1:20000/health"
        dependencies: ["Consul"]

    - APIGateway:
        script: "/home/yomu/agent/Service/Gateway/APIGateway.py"
        service_name: "APIGateway"
        conda_env: "/home/yomu/data/anaconda3/envs/agent"
        args: []
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "APIGateway.log"
        startup_timeout: 30
        health_check_url: "http://127.0.0.1:20001/health"
        dependencies: ["MicroServiceGateway"]

    # Agent 客户端模块已移至 InternalModuleInit 管理
    # - OllamaAgent: 现由 InternalModuleInit 管理
    # - GPTSovitsAgent: 现由 InternalModuleInit 管理

    - MySQLService:
        script: "/home/yomu/agent/Service/MySQLService/MySQLService.py"
        service_name: "MySQLAgent"
        conda_env: "/home/yomu/data/anaconda3/envs/agent"
        args: []
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "MySQLService.log"
        health_check_url: "http://127.0.0.1:20050/health"
        startup_timeout: 30

    - UserService:
        script: "/home/yomu/agent/Service/UserService/app/main.py"
        service_name: "UserService"
        conda_env: "/home/yomu/data/anaconda3/envs/agent"
        args: []
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "UserService.log"
        startup_timeout: 30
        health_check_url: "http://127.0.0.1:20010/health"
        dependencies: ["MySQLAgent"]

    # 其他业务模块已移至 InternalModuleInit 管理
    # - ChatModule: 现由 InternalModuleInit 管理
    # - SenseVoiceAgent: 现由 InternalModuleInit 管理
    # - PromptOptimizer: 现由 InternalModuleInit 管理

  # (可选)启动的optional外部服务
  optional_services:
    # 示例可选服务配置
    # - YOLOAgent:
    #     script: "/home/yomu/agent/Module/Vision/YOLO/YOLOAgent.py"
    #     service_name: "YOLOAgent"
    #     conda_env: "/home/yomu/data/anaconda3/envs/yolo"
    #     args: []
    #     use_python: true
    #     run_in_background: true
    #     is_base: false
    #     log_file: "YOLOAgent.log"
    #     startup_timeout: 60
    
  # 目前已支持的外部服务（仅包含独立进程服务）
  support_services:
    - ollama_server
    - GPTSoVits_server
    - SenseVoice_server
    - Consul
    - MicroServiceGateway
    - APIGateway
    - MySQLService
    - UserService
    # Agent 客户端模块已移至 InternalModuleInit 管理
    - APIGateway
    - OllamaAgent
    - GPTSovitsAgent
    - MySQLService
    - UserService
    - ChatModule
    - SenseVoiceAgent
    - PromptOptimizer
    
  # 待支持的外部服务
  #_services:
  #  - yolo11 
  
  # 外部服务器 IP 地址和端口配置
  # TODO 后期修改0.0.0.0，让其只监听本地
  ip_port:
    - ollama_server: ["127.0.0.1","11434"]
    - GPTSoVits: ["127.0.0.1","9880"]
    - SenseVoice: ["127.0.0.1","20042"]
    - Consul: ["127.0.0.1","8500"]
    - MicroServiceGateway: ["127.0.0.1","20000"]
    - APIGateway: ["127.0.0.1","20001"]
    - OllamaAgent: ["127.0.0.1","20030"]
    - GPTSovitsAgent: ["127.0.0.1","20040"]
    - MySQLService: ["127.0.0.1","20050"]
    - UserService: ["127.0.0.1","20010"]
    - ChatModule: ["127.0.0.1","20060"]
    - SenseVoiceAgent: ["127.0.0.1","20041"]
    - PromptOptimizer: ["127.0.0.1","20022"]
    
# ############################################################################################
# 重试配置
retry_config:
  max_retries: 3
  base_delay: 1.0
  max_delay: 60.0
  backoff_factor: 2.0

# 健康检查配置
health_check:
  default_timeout: 30
  check_interval: 2
  
# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# 进程管理配置
process_management:
  graceful_shutdown_timeout: 10
  force_kill_timeout: 5
