# 核心LLM采用Ollama的方式
# 默认使用llama3.2

model:
  name: llama3.2 # ollama运行的模型名称(必须在ollama中支持并且可以运行的，需要自行在ollama中下载)

# 要启动的核心模块
core_module: 
  - GPTSoVits
  - SenseVoice

# (可选)启动的功能模块
functional_module:
  - yolo11