# 核心LLM
    # 采用Ollama的方式默认使用llama3.2
LLM_model:
  name: llama3.2 # ollama运行的模型名称(必须在ollama中支持并且可以运行的)

############################################################################################
# 外部服务

# 要启动的基础外部服务
external_services:
  base_services:
  
    - Consul:
        script: "consul"
        service_name: "Consul"
        conda_env: "/home/yomu/data/anaconda3/envs"
        # args: ["agent", "-server", "-bind=127.0.0.1", "-client=127.0.0.1",
        # "-bootstrap-expect=3" ,"-node=consul-server-01" ,
        # "-data-dir=/home/yomu/data/consul_data/server01",
        # "-join=127.0.0.1:8300" ,"-http-port=8500" ,"-rpc-port=8300" ,"-server-port=8300"]
        args: ["agent", "-dev", "-client", '{{ GetPrivateInterfaces | exclude "type" "ipv6" | join "address" " " }} {{ GetAllInterfaces | include "flags" "loopback" | join "address" " " }}']
        use_python: false
        run_in_background: true
        is_base: true
        log_file: "Consul.log"

    - ollama_server:
        script: "ollama"
        service_name: "ollama_server"
        conda_env: "/home/yomu/data/anaconda3/envs"
        args: ["serve"]
        use_python: false
        run_in_background: true
        is_base: true
        log_file: "ollama_server.log"

    - GPTSoVits_server:
        script: "/home/yomu/GPTSoVits/GPTSoVits_api.py"
        service_name: "GPTSoVits_server"
        conda_env: "/home/yomu/data/anaconda3/envs/GPTSoVits"
        args: ["-a", "0.0.0.0","-p","9880"]
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "GPTSoVits_server.log"

    - SenseVoice_server:
        script: "/home/yomu/SenseVoice/SenseVoice_server.py"
        service_name: "SenseVoice_server"
        conda_env: "/home/yomu/data/anaconda3/envs/SenseVoice"
        args: []
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "SenseVoice_server.log"

    - MicroServiceGateway:
        script: "/home/yomu/agent/Service/Gateway/MicroServiceGateway.py"
        service_name: "MicroServiceGateway"
        conda_env: "/home/yomu/data/anaconda3/envs/agent"
        args: []
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "MicroServiceGateway.log"

    - APIGateway:
        script: "/home/yomu/agent/Service/Gateway/APIGateway.py"
        service_name: "APIGateway"
        conda_env: "/home/yomu/data/anaconda3/envs/agent"
        args: []
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "APIGateway.log"

    - OllamaAgent:
        script: "/home/yomu/agent/Module/LLM/OllamaAgent.py"
        service_name: "OllamaAgent"
        conda_env: "/home/yomu/data/anaconda3/envs/agent"
        args: []
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "OllamaAgent.log"

    - GPTSovitsAgent:
        script: "/home/yomu/agent/Module/TTS/GPTSoVits/GPTSoVitsAgent.py"
        service_name: "GPTSovitsAgent"
        conda_env: "/home/yomu/data/anaconda3/envs/agent"
        args: []
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "GPTSovitsAgent.log"

    - MySQLAgent:
        script: "/home/yomu/agent/Module/Utils/Database/MySQLAgent.py"
        service_name: "MySQLAgent"
        conda_env: "/home/yomu/data/anaconda3/envs/agent"
        args: []
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "MySQLAgent.log"

    - UserService:
        script: "/home/yomu/agent/Service/Other/UserService.py"
        service_name: "UserService"
        conda_env: "/home/yomu/data/anaconda3/envs/agent"
        args: []
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "UserService.log"

    - ChatModule:
        script: "/home/yomu/agent/Module/Chat/ChatModule.py"
        service_name: "ChatModule"
        conda_env: "/home/yomu/data/anaconda3/envs/agent"
        args: []
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "ChatModule.log"

    - SenseVoiceAgent:
        script: "/home/yomu/agent/Module/STT/SenseVoice/SenseVoiceAgent.py"
        service_name: "SenseVoiceAgent"
        conda_env: "/home/yomu/data/anaconda3/envs/agent"
        args: []
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "SenseVoiceAgent.log"

    - PromptOptimizer:
        script: "/home/yomu/agent/Module/Input/PromptOptimizer.py"
        service_name: "PromptOptimizer"
        conda_env: "/home/yomu/data/anaconda3/envs/agent"
        args: []
        use_python: true
        run_in_background: true
        is_base: true
        log_file: "PromptOptimizer.log"

  # (可选)启动的optional外部服务
  optional_services:
    
  # 目前已支持的外部服务
  support_services:
    - ollama
    - GPTSoVits
    - SenseVoice
  # 待支持的外部服务
  #_services:
  #  - yolo11 
  # TODO 后期修改0.0.0.0，让其只监听本地
  # 外部服务器ipaddress---port
  ip_port:
    - ollama_server: ["127.0.0.1","11434"]
    - GPTSoVits: ["127.0.0.1","9880"]
    - SenseVoice: ["127.0.0.1","9890"]

############################################################################################

### 内部模块

# 要启动的基础模块
internal_modules:
  base_modules: 
    - GPTSoVitsAgent: Module.TTS.GPTSoVits.GPTSoVitsAgent
    - SenseVoiceAgent: Module.STT.SenseVoice.SenseVoiceAgent
    - OllamaAgent: Module.LLM.OllamaAgent
    - ChatModule: Module.Chat.ChatModule
    - PromptOptimizer: Module.Input.PromptOptimizer
  # (可选)启动的optional功能模块
  optional_modules:
    
  # 目前已支持的内部模块
  support_modules:
    - GPTSoVitsAgent
    - SenseVoiceAgent
    - OllamaAgent
    - ChatModule
    - PromptOptimizer
  # 待支持的内部模块
  #_module:
  #  - yolo11: Module.Utils.yolo11

############################################################################################