# 服务发现配置文件

service_discovery:
  # 必需的外部服务列表
  required_services:
    - "ollama_server"      # LLM服务
    - "GPTSoVits_server"   # TTS服务  
    - "SenseVoice_server"  # STT服务

  # 服务名称映射 (Consul服务名 -> 内部服务名)
  service_mapping:
    "ollama_server": "llm_service"
    "GPTSoVits_server": "tts_service"
    "SenseVoice_server": "stt_service"

  # Consul配置
  consul:
    url: "http://127.0.0.1:8500"
    timeout: 10
    retry_count: 3
    retry_delay: 2

  # 健康检查配置
  health_check:
    timeout: 5           # 健康检查超时时间（秒）
    retry_count: 3       # 重试次数
    retry_delay: 2       # 重试间隔（秒）
    interval: 30         # 定期健康检查间隔（秒）

  # 服务端点配置
  service_endpoints:
    ollama_server:
      health_check: "/api/tags"
      api_prefix: "/api"
    
    GPTSoVits_server:
      health_check: "/health"
      api_prefix: ""
    
    SenseVoice_server:
      health_check: "/health"
      api_prefix: ""

  # 连接配置
  connection:
    timeout: 10.0        # 请求超时时间
    read_timeout: 60.0   # 读取超时时间
    max_connections: 100 # 最大连接数
    max_keepalive: 20    # 最大保持连接数
    follow_redirects: true

  # 服务等待配置
  startup:
    wait_timeout: 60     # 等待服务启动超时（秒）
    check_interval: 5    # 检查间隔（秒）
    max_retries: 12      # 最大重试次数

  # 故障恢复配置
  recovery:
    auto_reconnect: true      # 自动重连
    reconnect_delay: 5        # 重连延迟（秒）
    max_reconnect_attempts: 5 # 最大重连尝试次数
    circuit_breaker: false    # 断路器（暂未实现）
