# 微服务网关配置
MicroserviceGateway:
  host: 0.0.0.0
  port: 20000
  internal_routes:
    TTSAgent: "http://tts_agent/"
    STTAgent: "http://stt_agent/"
    LLMAgent: "http://llm_agent/"
    UserService: "http://user_service/"

############################################################################################

# API网关配置
APIGateway:
  host: 0.0.0.0
  port: 20001
  routes:
    UserService: "http://127.0.0.1:20010"
    MicroserviceGateway: "http://127.0.0.1:20000"
    
# "/agent/chat/input/text": "http://chat_service/input/text"
# "/agent/chat/input/audio": "http://chat_service/input/audio"
# "/agent/chat/input/streaming_audio": "http://chat_service/input/streaming_audio"
# "/agent/chat/input/video": "http://chat_service/input/video"
# "/agent/chat/input/streaming_video": "http://chat_service/input/streaming_video"


############################################################################################