# OllamaAgent配置
OllamaAgent:
  # 微服务本身的地址和端口
  host: 127.0.0.1
  port: 20030

  # Ollama 的url
  ollama_url: "http://127.0.0.1:11434"

  # Consul 服务器的 URL，包括协议前缀
  consul_url: "http://127.0.0.1:8500"

  # 健康检查的 URL
  health_check_url: "http://127.0.0.1:20030/health"  # 可选，默认会自动生成

  # 当前微服务的名称和唯一标识符
  service_name: "OllamaAgent"
  service_id: "OllamaAgent-127.0.0.1:20030"  # 可选，默认会自动生成
