# 用户服务配置
UserService:
  # 微服务本身的地址和端口
  host: 127.0.0.1
  port: 20010

  # Consul 服务器的 URL，包括协议前缀
  consul_url: "http://127.0.0.1:8500"

  # 需要通过 Consul 进行服务发现的微服务列表
  services:
    - "MySQLAgent"

  # 健康检查的 URL
  health_check_url: "http://127.0.0.1:20010/health"  # 可选，默认会自动生成

  # 当前微服务的名称和唯一标识符
  service_name: "UserService"
  service_id: "UserService-127.0.0.1:20010"  # 可选，默认会自动生成

  # jwt加密配置
  jwt:
    secret_key: "your_secret_key"
    algorithm: "HS256"
    expiration: 3600
